#!/usr/bin/env python3
"""Generate C++ pybind11 bindings and Python type stubs from native_functions.yaml."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import yaml


@dataclass
class Argument:
    name: str
    type: str


@dataclass
class Function:
    name: str
    cpp_name: str
    doc: str
    args: list[Argument]
    returns: str


def _load_functions(path: Path) -> list[Function]:
    with path.open("r", encoding="utf-8") as handle:
        entries = yaml.safe_load(handle)

    functions: list[Function] = []
    for entry in entries:
        args = [Argument(name=arg["name"], type=arg["type"]) for arg in entry["args"]]
        functions.append(
            Function(
                name=entry["name"],
                cpp_name=entry["cpp_name"],
                doc=entry.get("doc", ""),
                args=args,
                returns=entry["returns"],
            )
        )
    return functions


def _render_bindings(functions: Iterable[Function]) -> str:
    lines = [
        "// Generated by tools/codegen.py. Do not edit manually.",
        "#include <pybind11/pybind11.h>",
        "#include <pybind11/stl.h>",
        "#include \"native_ops.h\"",
        "#include \"tensor.h\"",
        "",
        "namespace py = pybind11;",
        "",
        "PYBIND11_MODULE(_ops, m) {",
        "  py::class_<Tensor>(m, \"Tensor\")",
        "      .def(py::init<std::vector<float>, std::vector<int64_t>>(),",
        "           py::arg(\"data\"), py::arg(\"shape\"))",
        "      .def_readonly(\"data\", &Tensor::data)",
        "      .def_readonly(\"shape\", &Tensor::shape);",
        "",
    ]

    for func in functions:
        arg_list = ", ".join(f"py::arg(\"{arg.name}\")" for arg in func.args)
        lines.append(
            f"  m.def(\"{func.name}\", &{func.cpp_name}, {arg_list}, \"{func.doc}\");"
        )

    lines.append("}")
    return "\n".join(lines) + "\n"


def _render_pyi(functions: Iterable[Function]) -> str:
    lines = [
        "# Generated by tools/codegen.py. Do not edit manually.",
        "from __future__ import annotations",
        "from typing import List",
        "",
        "class Tensor:",
        "    data: List[float]",
        "    shape: List[int]",
        "",
        "    def __init__(self, data: List[float], shape: List[int]) -> None: ...",
        "",
    ]

    type_map = {
        "Tensor": "Tensor",
        "float": "float",
    }

    for func in functions:
        args = ", ".join(f"{arg.name}: {type_map[arg.type]}" for arg in func.args)
        returns = type_map.get(func.returns, func.returns)
        lines.append(f"def {func.name}({args}) -> {returns}: ...")

    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--yaml", default="native_functions.yaml")
    parser.add_argument("--cpp-out", default="src/generated_bindings.cpp")
    parser.add_argument("--pyi-out", default="python/aten_codegen_example/_ops.pyi")
    args = parser.parse_args()

    functions = _load_functions(Path(args.yaml))

    cpp_out = Path(args.cpp_out)
    cpp_out.write_text(_render_bindings(functions), encoding="utf-8")

    pyi_out = Path(args.pyi_out)
    pyi_out.write_text(_render_pyi(functions), encoding="utf-8")


if __name__ == "__main__":
    main()
