// Generated by tools/codegen.py. Do not edit manually.
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include "native_ops.h"
#include "tensor.h"

namespace py = pybind11;

PYBIND11_MODULE(_ops, m) {
  py::class_<Tensor>(m, "Tensor")
      .def(py::init<std::vector<float>, std::vector<int64_t>>(),
           py::arg("data"), py::arg("shape"))
      .def_readonly("data", &Tensor::data)
      .def_readonly("shape", &Tensor::shape);

  m.def("add_scalar", &add_scalar, py::arg("self"), py::arg("other"), "Add a scalar to every element in a Tensor.");
  m.def("mul_scalar", &mul_scalar, py::arg("self"), py::arg("other"), "Multiply every element in a Tensor by a scalar.");
}
