# Generated by tools/codegen.py. Do not edit manually.
from __future__ import annotations
from typing import List

class Tensor:
    data: List[float]
    shape: List[int]

    def __init__(self, data: List[float], shape: List[int]) -> None: ...

def add_scalar(self: Tensor, other: float) -> Tensor: ...
def mul_scalar(self: Tensor, other: float) -> Tensor: ...
